name: geohash_plus_firestore
description: Geo query in Firestore using geohash_plus, a customizable Geohash. You can search for documents within a rectangle.
version: 1.1.0
homepage: https://github.com/zuvola/geohash_plus_firestore

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.4.7
  flutter:
    sdk: flutter
  geohash_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fake_cloud_firestore: ^1.3.1

flutter:
